#!/usr/bin/env python3
"""Generate the module's 8x8 bitmap font (ASCII 32..126) as a C header.

The TRACE module draws its own chrome -- funds, date, population, the tool
palette -- so it needs a font of its own. Rendering one here keeps the module
free of any font dependency at runtime: it ends up as 760 bytes of constant.

Usage: make_font.py <out.h> [font.ttf] [size]
"""
import sys

from PIL import Image, ImageDraw, ImageFont

FIRST, LAST = 32, 126
W = H = 8


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else "font8x8.h"
    path = sys.argv[2] if len(sys.argv) > 2 else \
        "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf"
    size = int(sys.argv[3]) if len(sys.argv) > 3 else 9

    font = ImageFont.truetype(path, size)
    rows = []
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        # Render oversized, threshold, then centre the ink in the 8x8 cell --
        # drawing straight into 8x8 leaves glyphs hard left and clipped.
        big = Image.new("L", (W * 3, H * 3), 0)
        ImageDraw.Draw(big).text((W, H // 2), ch, font=font, fill=255)
        mask = big.point(lambda v: 255 if v > 110 else 0)
        box = mask.getbbox()
        img = Image.new("L", (W, H), 0)
        if box:
            ink = mask.crop(box)
            if ink.width > W or ink.height > H:
                ink = ink.crop((0, 0, min(ink.width, W), min(ink.height, H)))
            img.paste(ink, ((W - ink.width) // 2, (H - ink.height + 1) // 2))
        px = img.load()
        glyph = []
        for y in range(H):
            bits = 0
            for x in range(W):
                if px[x, y] > 110:          # already thresholded above
                    bits |= 0x80 >> x
            glyph.append(bits)
        rows.append((code, ch, glyph))

    with open(out, "w") as fh:
        fh.write("// Generated by tools/make_font.py -- do not edit.\n")
        fh.write("// 8x8, ASCII %d..%d, one byte per row, bit 7 = leftmost pixel.\n"
                 % (FIRST, LAST))
        fh.write("#pragma once\n#include <stdint.h>\n\n")
        fh.write("#define FONT_FIRST %d\n#define FONT_LAST %d\n" % (FIRST, LAST))
        fh.write("#define FONT_W %d\n#define FONT_H %d\n\n" % (W, H))
        fh.write("static const uint8_t font8x8[%d][%d] = {\n" % (LAST - FIRST + 1, H))
        for code, ch, glyph in rows:
            shown = ch if ch not in ('\\', "'") else '\\' + ch
            fh.write("    {%s}, // %d '%s'\n"
                     % (",".join("0x%02X" % b for b in glyph), code, shown))
        fh.write("};\n")
    print("%s: %d glyphs from %s at %d px" % (out, len(rows), path, size))

    # Rough preview so a bad threshold is obvious at a glance.
    for code in (ord('A'), ord('M'), ord('8'), ord('$')):
        glyph = rows[code - FIRST][2]
        print("'%s'" % chr(code))
        for b in glyph:
            print("  " + "".join('#' if b & (0x80 >> i) else '.' for i in range(W)))


if __name__ == "__main__":
    main()
